# Generated by Django 6.0.6 on 2026-07-06 03:40

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=apps.orders.models.generate_order_id, max_length=32, unique=True, verbose_name='订单号')),
                ('type', models.CharField(choices=[('course_consulting', '课程咨询'), ('private_training', '私教指导'), ('event_signup', '活动报名'), ('equipment', '器械定制'), ('other', '其他')], default='other', max_length=30, verbose_name='报单类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='状态')),
                ('contact_name', models.CharField(max_length=64, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('description', models.TextField(verbose_name='需求描述')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='金额(元)')),
                ('review_note', models.CharField(blank=True, max_length=300, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报单',
                'verbose_name_plural': '报单',
                'ordering': ['-created_at'],
            },
        ),
    ]
