# Generated by Django 6.0.6 on 2026-07-06 03:40

import apps.points.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='商品名称')),
                ('desc', models.CharField(blank=True, max_length=300, verbose_name='商品描述')),
                ('points_cost', models.PositiveIntegerField(verbose_name='所需积分')),
                ('is_vip', models.BooleanField(default=False, verbose_name='是否 VIP 商品')),
                ('vip_days', models.PositiveIntegerField(default=0, verbose_name='VIP 天数')),
                ('status', models.CharField(choices=[('active', '上架'), ('inactive', '下架')], default='active', max_length=10, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=50, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '兑换商品',
                'verbose_name_plural': '兑换商品',
                'ordering': ['-sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PointLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.CharField(default=apps.points.models.generate_ledger_id, max_length=32, unique=True, verbose_name='流水号')),
                ('type', models.CharField(choices=[('grant', '管理员发放'), ('adjustment', '管理调整'), ('course_enroll', '课程报名'), ('vip_exchange', 'VIP 兑换'), ('exchange', '商品兑换'), ('register', '注册奖励'), ('invite', '邀请奖励')], max_length=20, verbose_name='类型')),
                ('change', models.IntegerField(help_text='正数增加,负数扣减', verbose_name='变动值')),
                ('title', models.CharField(max_length=200, verbose_name='摘要')),
                ('balance_after', models.IntegerField(verbose_name='变动后余额')),
                ('ref_id', models.CharField(blank=True, max_length=64, verbose_name='关联业务 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(default=apps.points.models.generate_exchange_id, max_length=32, unique=True, verbose_name='兑换单号')),
                ('item_title', models.CharField(max_length=120, verbose_name='商品名称快照')),
                ('points_cost', models.PositiveIntegerField(verbose_name='消耗积分')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('processed', '已处理'), ('cancelled', '已取消')], default='submitted', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='points.exchangeitem', verbose_name='兑换商品')),
            ],
            options={
                'verbose_name': '兑换记录',
                'verbose_name_plural': '兑换记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
