# Generated by Django 6.0.6 on 2026-07-06 03:40

import apps.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default=apps.services.models.generate_service_id, max_length=32, unique=True, verbose_name='服务编号')),
                ('name', models.CharField(max_length=120, verbose_name='服务名称')),
                ('desc', models.TextField(blank=True, verbose_name='服务描述')),
                ('icon', models.URLField(blank=True, verbose_name='图标')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格(元)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='划线价(元)')),
                ('points_cost', models.PositiveIntegerField(default=0, verbose_name='积分价格')),
                ('features', models.CharField(blank=True, help_text='逗号分隔', max_length=300, verbose_name='服务特性')),
                ('sort_order', models.IntegerField(default=50, verbose_name='排序权重')),
                ('status', models.CharField(choices=[('active', '上架'), ('inactive', '下架')], default='active', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务套餐',
                'verbose_name_plural': '服务套餐',
                'ordering': ['-sort_order', 'id'],
            },
        ),
    ]
