# Generated by Django 6.0.6 on 2026-07-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='摘要')),
                ('content', models.TextField(blank=True, verbose_name='正文')),
                ('cover', models.URLField(blank=True, verbose_name='封面图')),
                ('author', models.CharField(blank=True, max_length=64, verbose_name='作者')),
                ('source_url', models.URLField(blank=True, verbose_name='公众号原文链接')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='published', max_length=10, verbose_name='状态')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '武学文章',
                'verbose_name_plural': '武学文章',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('desc', models.CharField(blank=True, max_length=300, verbose_name='描述')),
                ('channel', models.CharField(choices=[('heritage', '武学传承'), ('shortdrama', '武学短剧')], default='heritage', max_length=20, verbose_name='频道')),
                ('cover', models.URLField(blank=True, verbose_name='封面图')),
                ('video_url', models.URLField(blank=True, verbose_name='视频地址')),
                ('duration', models.CharField(blank=True, max_length=16, verbose_name='时长')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='published', max_length=10, verbose_name='状态')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='播放量')),
                ('sort_order', models.IntegerField(default=50, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '短视频',
                'verbose_name_plural': '短视频',
                'ordering': ['-sort_order', '-created_at'],
            },
        ),
    ]
