# Generated by Django 6.0.6 on 2026-07-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(blank=True, max_length=64, verbose_name='操作者名称')),
                ('module', models.CharField(choices=[('users', '用户管理'), ('points', '积分管理'), ('orders', '报单管理'), ('courses', '课程管理'), ('services', '服务管理'), ('messages', '消息管理'), ('content', '内容管理'), ('vip', 'VIP 管理'), ('system', '系统设置')], max_length=20, verbose_name='模块')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('approve', '通过'), ('reject', '拒绝'), ('grant', '发放'), ('revoke', '撤销')], max_length=20, verbose_name='操作')),
                ('target_type', models.CharField(blank=True, max_length=64, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='目标 ID')),
                ('detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作者 IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
