# Generated by Django 6.0.6 on 2026-07-06 03:40

import apps.courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default=apps.courses.models.generate_course_id, max_length=32, unique=True, verbose_name='课程编号')),
                ('title', models.CharField(max_length=120, verbose_name='课程标题')),
                ('desc', models.TextField(blank=True, verbose_name='课程简介')),
                ('content', models.TextField(blank=True, verbose_name='课程详情')),
                ('cover', models.URLField(blank=True, verbose_name='封面图')),
                ('category', models.CharField(choices=[('fist_forms', '拳法套路'), ('internal_arts', '内功心法'), ('weapons', '器械兵器'), ('philosophy', '武道哲学'), ('wellness', '养生健身'), ('shortdrama', '武学短剧'), ('heritage', '武学传承')], max_length=20, verbose_name='分类')),
                ('teacher', models.CharField(blank=True, max_length=64, verbose_name='讲师')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='售价(元)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='划线价(元)')),
                ('points_cost', models.PositiveIntegerField(default=0, verbose_name='积分价格')),
                ('tags', models.CharField(blank=True, help_text='逗号分隔,如: 热门,推荐,新课', max_length=200, verbose_name='标签')),
                ('lesson_count', models.PositiveIntegerField(default=0, verbose_name='课时数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已下架')], default='draft', max_length=10, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=50, verbose_name='排序权重')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('enroll_count', models.PositiveIntegerField(default=0, verbose_name='报名人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '武学课程',
                'verbose_name_plural': '武学课程',
                'ordering': ['-sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='章节标题')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='排序序号')),
                ('is_free', models.BooleanField(default=False, verbose_name='免费试看')),
                ('video_url', models.URLField(blank=True, verbose_name='视频地址')),
                ('duration', models.CharField(blank=True, help_text='如 12:30', max_length=16, verbose_name='时长')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_paid', models.PositiveIntegerField(default=0, verbose_name='支付积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '修习报名',
                'verbose_name_plural': '修习报名',
                'ordering': ['-created_at'],
            },
        ),
    ]
