# Generated by Django 6.0.6 on 2026-07-06 03:40

import apps.users.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='手机号')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, max_length=64, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('role', models.CharField(choices=[('client', '普通学员'), ('member', '会员'), ('consultant', '咨询师'), ('admin', '运营管理员'), ('super_admin', '超级管理员')], default='client', max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('active', '正常'), ('banned', '已禁用')], default='active', max_length=10, verbose_name='账号状态')),
                ('points', models.IntegerField(default=0, verbose_name='积分余额')),
                ('total_points', models.IntegerField(default=0, verbose_name='历史总获得积分')),
                ('used_points', models.IntegerField(default=0, verbose_name='历史总消耗积分')),
                ('member_code', models.CharField(blank=True, max_length=32, verbose_name='会员编码')),
                ('invite_code', models.CharField(default=apps.users.models.generate_invite_code, max_length=16, unique=True, verbose_name='邀请码')),
                ('vip_level', models.PositiveSmallIntegerField(default=0, verbose_name='VIP 等级')),
                ('vip_expire_at', models.DateTimeField(blank=True, null=True, verbose_name='VIP 到期时间')),
                ('vip_exchanged_at', models.DateTimeField(blank=True, null=True, verbose_name='VIP 兑换时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '武学修习者',
                'verbose_name_plural': '武学修习者',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
