# Generated by Django 6.0.6 on 2026-07-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('system', '系统通知'), ('order', '报单通知'), ('course', '课程通知'), ('points', '积分通知')], default='system', max_length=10, verbose_name='类型')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '消息通知',
                'verbose_name_plural': '消息通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
